#!/bin/bash
set -ue

readonly ext_name="json-bookmarks"

get_version()
{
  git describe --tags --dirty
}

get_mainfest_version()
{
  local semver="$(git describe --tags --abbrev=0)"
  echo "${semver#v}"
}

create_manifest_for()
{
  browser_vendor="${1}"
  version="$(get_mainfest_version)" envsubst < manifest.${browser_vendor}.json.in > manifest.json
}

create_package_for()
{
  browser_vendor="${1}"
  create_manifest_for "${browser_vendor}"
  mkdir --parents "out/"
  zip \
    --recurse-paths \
    --filesync \
    out/${ext_name}-${browser_vendor}-$(get_version).zip \
    bookmark \
    icon \
    third_party \
    *.js \
    *.html \
    *.css \
    LICENSE \
    manifest.json
}

create_package_for "mozilla"
create_package_for "chrome"
